# Generated by Django 4.0.4 on 2022-06-08 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people_title', models.CharField(max_length=100)),
                ('people_name', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=20)),
                ('product_category', models.CharField(max_length=20)),
                ('product_price', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=20)),
                ('patients', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybio.people')),
            ],
        ),
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(default='ofoh@gmail.com', max_length=254)),
                ('age', models.CharField(max_length=3)),
                ('friends', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybio.people')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_address', models.CharField(max_length=100)),
                ('postcode', models.CharField(max_length=20)),
                ('address_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mybio.people')),
            ],
        ),
    ]
